name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    name: EAS Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Standalone APK on Expo Cloud
        run: eas build --platform android --profile preview --non-interactive
        
